check_hprparams – Basic Optimization Framework - FORTRAN 90
check_hprparams Subroutine
34 statements
Source File
public subroutine check_hprparams(nb_hprparams, hprnames, hprdata, hprdim, hprbool, requiredbool)
Subroutine for checking which hyper parameters were informed by the user.
This subroutine starts where the handle_hyp_file(...) subroutine stops, and is written separately only for clarity. It checks if all required hyper parameters have been defined (and will halt execution if not). If optional hyper parameters haven't been specified, then it warns the user and shows them the default values used.
Note
Default values for optional hyper parameters must be defined in the optimization procedure before calling the handle_hyp_file(...) subroutine, by initializing the associated elements of the hprdata array.
ARGUMENTS are explained in the handle_hyp_file(...) subroutine's documentation
Arguments
Type Intent Optional Attributes Name
integer :: nb_hprparams
character(len=256), dimension(nb_hprparams) :: hprnames
Hyperparameter names.
real(kind=8), dimension(nb_hprparams, dimx) :: hprdata
Where data will be saved
integer, dimension(nb_hprparams) :: hprdim
Dimension of each hprparam.
logical, dimension(nb_hprparams) :: hprbool
Bool array: hprparam present or not
logical, dimension(nb_hprparams) :: requiredbool
Bool array: hprparam optional or not
Called by
Call graph
handle_hyp_file calls check_hprparams
gd calls handle_hyp_file
handle_main_file calls gd
main calls handle_main_file