check_status – Basic Optimization Framework - FORTRAN 90
check_status Subroutine
8 statements
Source File
public subroutine check_status(filestatus, errormsg)
Subroutine for handling file reading errors.
This subroutine takes directly the iostat and iomsg values from the file opening procedure.
ARGUMENTS
filestatus : integer The iostat value.
errormsg : character*256 The associated error message.
Arguments
Type Intent Optional Attributes Name
integer :: filestatus
File reading status (indicates errors)
character(len=256) :: errormsg
Error message and read line
Called by
Call graph
handle_hyp_file calls check_status
handle_main_file calls check_status, gd
gd calls handle_hyp_file
main calls handle_main_file