handle_main_file – Basic Optimization Framework - FORTRAN 90
handle_main_file Subroutine
127 statements
Source File
public subroutine handle_main_file(nb_methods, nb_rprt_params, method_names, rprt_params)
Subroutine for handling the optimization runs.
This subroutine reads the main.txt file and interpets its contents.
This means reading the optimization methods, the report parameters (types of output, number of times a certain optimization should be run, etc.) and calling the corresponding optimization subroutine and passing it the important hyperparameter information.
As of know, in order to maintain the current implementation, the method's hyperparameters are written to the output/hyperparams.txt file (deleted at the end of execution). This is surely not the best way to do this (passing the character variable directly to the method ought to be more efficient). This is an improvement that can be done in the future (changing the handle_hyp_file subroutine) and how its called in the optimization methods.
Arguments
Type Intent Optional Attributes Name
integer :: nb_methods
The total number of optimization methods currently implemented
integer :: nb_rprt_params
Number of report parameters currently implemented.
character(len=20), dimension(nb_methods) :: method_names
Array of optimization methods' names/labels.
character(len=256), dimension(nb_rprt_params) :: rprt_params
Array of report parameters' names/labels.
Calls
Called by
Call graph
handle_main_file calls check_status, gd
gd calls dfn_dx, fn, format_data, handle_hyp_file
handle_hyp_file calls check_status, check_hprparams
main calls handle_main_file